import { useEffect,useRef,useState } from 'react';
import { Piano,RefreshCw,Play,Pause,Square,SkipForward,Volume2,Music2,ChevronDown,Check,Headphones,ArrowRight,LoaderCircle,SlidersHorizontal } from 'lucide-react';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import Score from '@/components/Score';
import { generate,type ComposeOptions } from '@/lib/music/compose';
import { gradeRule,rules } from '@/lib/music/abrsmGradeRules';
import { type Exercise,type Grade,barTicks,PPQ } from '@/lib/music/model';
import { PianoPlayer,type PlaybackState } from '@/lib/music/player';
import { secondsAtTick } from '@/lib/music/events';
const randomSeed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
const formatTime=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
export default function Home(){
 const [grade,setGrade]=useState<Grade>(1),[exercise,setExercise]=useState<Exercise|null>(null),[tempo,setTempo]=useState(72),[countIn,setCountIn]=useState(true),[metronome,setMetronome]=useState(false),[loop,setLoop]=useState(false),[state,setState]=useState<PlaybackState>('idle'),[tick,setTick]=useState(0),[count,setCount]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[engraved,setEngraved]=useState(false),[about,setAbout]=useState(false);
 const player=useRef<PianoPlayer|null>(null),generation=useRef(0);
 const options={tempo,countIn,metronome,loop};
 function newExercise(g=grade,seed=randomSeed(),config:ComposeOptions={}){const request=++generation.current;player.current?.stop();setBusy(true);setError('');setEngraved(false);setExercise(null);setTimeout(()=>{if(request!==generation.current)return;try{const e=generate(g,seed,config);setExercise(e);setTempo(e.tempo);}catch(err){setError((err as Error).message);}finally{setBusy(false);}},30);}
 useEffect(()=>{player.current=new PianoPlayer((s,t,c)=>{setState(s);setTick(t);setCount(c);});const query=new URLSearchParams(location.search);const g=(import.meta.env.DEV?Math.max(1,Math.min(8,Number(query.get('grade'))||1)):1) as Grade;setGrade(g);const config:ComposeOptions=import.meta.env.DEV?{key:query.get('key')??undefined,metre:query.get('metre')??undefined,feature:(query.get('feature')??undefined) as ComposeOptions['feature']}:{};newExercise(g,import.meta.env.DEV&&query.has('seed')?Number(query.get('seed')):randomSeed(),config);return()=>{generation.current++;player.current?.dispose();};},[]);
 useEffect(()=>{player.current?.setOptions(options);},[tempo,countIn,metronome,loop]);
 async function togglePlay(){if(!exercise)return;if(state==='playing'){player.current?.pause();return;}setError('');try{await player.current?.play(exercise,options);}catch(err){setError((err as Error).message);}}
 const duration=exercise?secondsAtTick(exercise,barTicks(exercise.metre)*exercise.measures.length,tempo):0,elapsed=exercise?secondsAtTick(exercise,tick,tempo):0;
 return <div className="app-shell">
  <header className="masthead"><a className="brand" href="/" aria-label="Prima home"><span className="brand-mark"><Piano size={22}/></span><span>prima<span className="brand-dot">.</span></span></a><span className="masthead-label">THE SIGHT-READING STUDIO</span><button className="text-button" onClick={()=>setAbout(!about)}>About the practice <ChevronDown size={15}/></button></header>
  {about&&<section className="about-panel"><strong>A little reading, every day.</strong><p>Choose your grade, take a moment to read, and try the piece on your own piano. Then listen and compare for yourself. There are no scores or saved attempts.</p><p>Based on ABRSM Piano Practical Grades 2025–2026. ABRSM confirms the 2027–2028 sight-reading requirements are unchanged. Independent practice tool; not official, endorsed by or affiliated with ABRSM.</p><a href="https://www.abrsm.org/sites/default/files/2024-06/Piano%202025%20%26%202026%20Prac%20syllabus%2020240524_access.pdf" target="_blank" rel="noreferrer">Read the official requirements ↗</a></section>}
  <main className="studio"><aside className="practice-panel"><div className="eyebrow">YOUR PRACTICE</div><h1>A fresh page.<br/>A little discovery.</h1><p className="intro">Make time for music you haven’t met yet.</p>
   <section className="grade-section"><div className="field-title"><label id="grade-label">Choose your grade</label><span>ABRSM 1–8</span></div><RadioGroup className="grade-grid" value={String(grade)} aria-labelledby="grade-label" onValueChange={v=>{const g=Number(v) as Grade;setGrade(g);newExercise(g);}}>{Array.from({length:8},(_,i)=>i+1).map(g=><label className={`grade-tile ${grade===g?'selected':''}`} key={g}><RadioGroupItem value={String(g)} aria-label={`Grade ${g}`}/><span>{g}</span></label>)}</RadioGroup><div className="grade-note"><span className="small-dot"/>Grade {grade}<span className="grade-level">{grade<=2?'Foundations':grade<=4?'Developing fluency':grade<=6?'Finding independence':'Advanced reading'}</span></div></section>
   <button className="generate-button" disabled={busy} onClick={()=>newExercise()}>{busy?<LoaderCircle className="spin" size={18}/>:<RefreshCw size={17}/>}Generate Exercise<ArrowRight size={18}/></button>
   <div className="practice-guide"><div className="eyebrow">A MOMENT BEFORE YOU PLAY</div><ol><li><span>1</span><div><strong>Read the page</strong><p>Notice the key, pulse and repeating shapes.</p></div></li><li><span>2</span><div><strong>Try it on your piano</strong><p>Keep going. Let the music flow.</p></div></li><li><span>3</span><div><strong>Listen and reflect</strong><p>Play the reference when you’re ready.</p></div></li></ol></div>
   <div className="private-note"><Headphones size={17}/><p>Your piano. Your pace.<br/><span>Just practice, without a score.</span></p></div>
  </aside>
  <section className="music-workspace"><div className="workspace-top"><div className="workspace-label"><Music2 size={16}/><span>SIGHT-READING PRACTICE</span></div><span className="grade-badge">GRADE {grade}</span></div>
   <article className="score-paper" data-grade={grade} aria-busy={!engraved||busy}><div className="paper-heading"><div><p className="exercise-label">Original ABRSM-aligned practice exercise</p><h2>{exercise?.title??'Preparing your music…'}</h2><div className="score-meta"><span>{exercise?.key??'—'}</span><i/><span>{exercise?.metre??'—'} time</span><i/><span>{exercise?.measures.length??'—'} bars</span><i/><span>{exercise?.style??'—'}</span></div></div><span className="paper-number">{String(grade).padStart(2,'0')}<small>GRADE</small></span></div>
    {exercise&&<Score exercise={exercise} tick={tick} playing={state==='playing'&&count===0} onReady={err=>{if(err==='loading'){setEngraved(false);return;}setEngraved(!err);if(err)setError(err);}}/>}
    {!engraved&&!error&&<div className="engraving-message"><LoaderCircle className="spin" size={16}/>Preparing your score…</div>}
    <div className="paper-footer"><span>{state==='playing'?(count?`Count in · ${count}`:`Reference · bar ${Math.min(exercise?.measures.length??1,Math.floor(tick/(exercise?barTicks(exercise.metre):192))+1)}`):state==='paused'?'Reference paused':'Take your time. Try it before listening.'}</span><span className="original-stamp"><span/>COMPOSED FOR THIS MOMENT</span></div>
   </article>
   {error&&<div className="error" role="alert">{error}<button onClick={()=>newExercise()}>Try another exercise</button></div>}
   <section className="playback-panel" aria-label="Reference playback"><div className="playback-main"><div className="transport"><button className="play-button" onClick={togglePlay} disabled={!engraved||busy||state==='loading'} aria-label={state==='playing'?'Pause':state==='paused'?'Resume':'Play'}>{state==='loading'?<LoaderCircle className="spin" size={19}/>:state==='playing'?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}<span>{state==='loading'?'Loading piano':state==='playing'?'Pause':state==='paused'?'Resume':'Play'}</span></button><button className="stop-button" aria-label="Stop" onClick={()=>player.current?.stop()}><Square size={17} fill="currentColor"/></button></div><div className="reference-time"><div><span><Volume2 size={14}/>Reference piano</span><span>{formatTime(elapsed)} <b>/ {formatTime(duration)}</b></span></div><div className="time-track"><span style={{width:`${duration?elapsed/duration*100:0}%`}}/></div></div><button className="skip-button" disabled={busy} onClick={()=>newExercise()}>Skip <SkipForward size={17}/></button></div>
    <div className="playback-options"><div className="tempo-control"><label id="tempo-label">Tempo</label><Slider aria-labelledby="tempo-label" aria-label="Tempo" value={[tempo]} min={40} max={140} step={1} onValueChange={value=>setTempo(Array.isArray(value)?value[0]:value)}/><span className="tempo-value">{tempo}<small> BPM ♩</small></span></div><div className="option-switches">{([{label:'Count-in',value:countIn,set:setCountIn},{label:'Metronome',value:metronome,set:setMetronome},{label:'Loop',value:loop,set:setLoop}]).map(o=><label className="switch-label" key={o.label}><Switch checked={o.value} onCheckedChange={o.set} aria-label={o.label}/>{o.label}</label>)}</div></div>
   </section><p className="self-check"><Check size={15}/>Listen, compare, and decide for yourself. Ready for a fresh start? Just skip.</p>
   <details className="exercise-details"><summary><SlidersHorizontal size={14}/>Exercise notes <ChevronDown size={13}/></summary><div className="detail-grid"><p><strong>Reading focus</strong>{gradeRule(grade).rationale}</p><p><strong>Musical shape</strong>{exercise?.phraseStructure.join(' + ')} bars · {exercise?.measures.map(m=>m.harmony).join(' – ')}</p></div><details><summary>Composition metadata</summary><pre>{JSON.stringify(exercise?{seed:exercise.seed,grade:exercise.grade,style:exercise.style,key:exercise.key,metre:exercise.metre,phraseStructure:exercise.phraseStructure,harmonicPlan:exercise.measures.map(m=>m.harmony),difficulty:exercise.difficulty,validation:exercise.validation,layout:exercise.layout}:null,null,2)}</pre></details></details>
  </section></main><footer className="site-footer"><span>prima. <span>A little music, every day.</span></span><span>Independent practice · No accounts · No tracking</span></footer>
 </div>;
}
