import { z } from 'zod';
import raw from './abrsmGradeRules.json';
import type { Grade } from './model';
const range=z.tuple([z.number(),z.number()]);
export const gradeSchema=z.object({grade:z.number().int().min(1).max(8),label:z.string(),rationale:z.string(),source:z.string(),introducedKeys:z.array(z.string()),keys:z.array(z.string()).min(1),metres:z.array(z.string().regex(/^\d+\/(4|8)$/)),length:z.object({min:z.number(),max:z.number(),target:z.number(),rationale:z.string()}),limits:z.object({maxNotesPerHand:z.number().int(),maxTotalNotes:z.number().int(),maxVoices:z.number().int(),maxMelodicLeap:z.number(),maxBassLeap:z.number(),maxHandSpan:z.number(),maxHandRange:z.number(),maxAccidentalsPerBar:z.number(),minNoteTicks:z.number(),maxAdvancedFamilies:z.number(),clefs:z.array(z.enum(['treble','bass'])),handsTogether:z.boolean()}),optionalFeatures:z.array(z.string()),hardExclusions:z.array(z.string()),dynamics:z.array(z.string()),musicality:z.object({minChordToneRatio:z.number(),minStepRatio:z.number(),maxRepeatedPitchRun:z.number(),maxIdenticalBarRun:z.number(),required:z.array(z.string())}),difficulty:z.object({minimum:z.number(),typical:range,maximum:z.number(),rationale:z.string()}),engraving:z.object({targetSystems:range,maxBarsPerSystem:z.number(),minBarsPerSystem:z.number(),maxWeightedSymbolsPerSystem:z.number(),minPageFill:z.number(),maxPageFill:z.number(),minOnsetsPerBar:z.number(),maxOnsetsPerBar:z.number()}),repertoireContext:z.unknown(),validation:z.array(z.string())});
export const rulesSchema=z.object({schemaVersion:z.string(),label:z.string(),audited:z.string(),syllabus:z.string(),upcoming:z.string(),affiliation:z.string(),featureGrade:z.record(z.string(),z.number().int()),grades:z.record(z.string(),gradeSchema)}).superRefine((r,c)=>{
 for(let g=1;g<=8;g++) { const x=r.grades[g]; if(!x||x.grade!==g) {c.addIssue({code:'custom',message:`Missing grade ${g}`});continue;} if(new Set(x.keys).size!==x.keys.length)c.addIssue({code:'custom',message:'Duplicate key'}); if(x.difficulty.minimum>x.difficulty.typical[0]||x.difficulty.typical[1]>x.difficulty.maximum)c.addIssue({code:'custom',message:'Invalid budget'}); if(g>1&&r.grades[g-1]?.keys.some(k=>!x.keys.includes(k)))c.addIssue({code:'custom',message:'Non-cumulative keys'}); }
});
export const rules=rulesSchema.parse(raw);
export const gradeRule=(g:Grade)=>rules.grades[String(g)];
